services:
  - type: web
    name: luna-bengkelin
    runtime: docker
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stderr